---
# tasks file for postfix
- name: configure debconf
  sudo: true
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: postfix_debconf_selections
  tags: [configuration, postfix, postfix-install]

- name: install package
  sudo: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items: postfix_install
  tags: [configuration, postfix, postfix-install]

- name: configure mailname
  sudo: true
  template:
    src: etc/mailname.j2
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  tags: [configuration, postfix, postfix-mailname]

- name: update configuration file
  sudo: true
  template:
    src: etc/postfix/main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  tags: [configuration, postfix, postfix-configuration]

- name: configure aliases
  sudo: true
  lineinfile:
    dest: /etc/aliases
    regexp: '^{{ item.user }}:\s+{{ item.alias }}'
    line: '{{ item.user }}: {{ item.alias }}'
    owner: root
    group: root
    mode: 0644
  with_items: postfix_aliases
  when: postfix_aliases
  notify:
    - new aliases
    - restart postfix
  tags: [configuration, postfix, postfix-aliases]

- name: start and enable service
  sudo: true
  service:
    name: postfix
    state: started
    enabled: yes
  tags: [configuration, postfix, postfix-start-enable-service]
